name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mlops-pipeline
  ACR_NAME: mlopsacr
  RESOURCE_GROUP: mlops-rg
  AKS_NAME: fraud-mlops-aks
  TF_DIR: infrastructure 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    #Azure Login
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

    #Terraform Init & Apply
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.2

    - name: Terraform Init
      working-directory: ${{ env.TF_DIR }}
      run: terraform init

    - name: Terraform Apply
      working-directory: ${{ env.TF_DIR }}
      run: terraform apply -auto-approve

    # ACR Build & Push
    - name: Azure ACR Login
      run: az acr login --name ${{ env.ACR_NAME }}

    - name: Build Docker Image
      run: docker build -t ${{ env.IMAGE_NAME }} .

    - name: Tag Docker Image for ACR
      run: docker tag ${{ env.IMAGE_NAME }} ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    - name: Push Docker Image to ACR
      run: docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    # AKS Deployment
    - name: Get AKS credentials
      run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_NAME }}

    - name: Deploy to AKS
      run: kubectl apply -f k8s/deployment.yaml
